### ISSUE TITLE
Outdated Browser Scripts are not working

### ISSUE THREAD

**Issue by Dalibor22x** [open-interactive/magnolia-megaton#115]

**Comment by pierresandrin-oi** [comment]
A js error in IE 9 made the js not load the outdated browser script. Doing it oldschool now.
![ie11_-_win7__running__und_megaton_development____documents_projekte_megaton_magnolia-megaton-development__-_____magnolia_light-modules_main_templates_pages_include_scripts_ftl__magnolia-starter-kit_](https://user-images.githubusercontent.com/24892583/48076918-7ff09100-e1e6-11e8-8f44-a80cd1102cc6.jpg)
