### ISSUE TITLE
Megaton Future

### ISSUE THREAD

**Issue by Fred-OI** [open-interactive/magnolia-megaton#119]

**Comment by pierresandrin-oi** [comment]
Grundsätzliches:
- Wie machen wir Releases? Wie Oft? Wie organisieren wir die Branches?
- Brauchen wir ein regelmässiges Megaton Meeting? Wie oft? (wöchentlich/monatlich/quartalsmässig)

**Comment by pierresandrin-oi** [comment]
**Craft CMS**
Kann man den Megaton FE Build im Craft verwenden?

**Comment by pierresandrin-oi** [comment]
**Issues**
Welche machen wir, wer? Welche schliessen wir.
Wo machen wir Issues? Canban board oder Github?

**Comment by pierresandrin-oi** [comment]
Moved to Wiki:
https://github.com/open-interactive/magnolia-megaton/wiki/Megaton-Meetings
