### ISSUE TITLE
Add lint for yaml

### ISSUE THREAD

**Issue by zischler** [open-interactive/magnolia-megaton#122]
lint for yaml so it sees if yaml files have errors.

**Comment by pierresandrin-oi** [comment]
ja, das will ich auch!

**Comment by pierresandrin-oi** [comment]
Thanks! We will try it out.

**Comment by pierresandrin-oi** [comment]
Install plugin snakeYaml for intellij and follow the instructions below:

_Note for Professional/Ultimate edition users
Those editions already include basic YAML support. In case you want to enable this plugin, you'll need to reassign file type mappings:
Go to `Preferences > Editor > File Types` and move `YAML` registered patterns to `SnakeYAML`._
