### ISSUE TITLE
Richtext configuration

### ISSUE THREAD

**Issue by pierresandrin-oi** [open-interactive/magnolia-megaton#88]
Problem with rich text fields. Maybe related to Magnolia 5.7

![magnolia_5_und_sympany_sharefile](https://user-images.githubusercontent.com/24892583/43124241-d4e597e0-8f26-11e8-9ba8-708c6239df6d.jpg)

**Comment by cedeber** [comment]
Which branch? I an currently working on the 5.0-beta.

**Comment by pierresandrin-oi** [comment]
4.1 beta
-- 
Open Interactive GmbH
Sempacherstrasse 17
4053 Basel
T +41 61 500 15 70
www.openinteractive.ch

**Comment by cedeber** [comment]
Look at the 5.0 then. This is the new 4.1 ;-) I changed the Editorial anyways.
The 4.1 is not planned to last. I renamed it v5 because of the novelties in the JS compilation.

**Comment by pierresandrin-oi** [comment]
Removed magnoliaFileBrowser from js config files. See:
https://jira.magnolia-cms.com/browse/MGNLUI-4524
